// Copyright 2021 The June Authors. All rights reserved.
// Use of this source code is governed by Apache License
// that can be found in the LICENSE file.

// Code generated by "stringer -type=ReadPolicy"; DO NOT EDIT.

package storestacked

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReadThrough-0]
	_ = x[ReadThroughCaching-1]
	_ = x[ReadAround-2]
}

const _ReadPolicy_name = "ReadThroughReadThroughCachingReadAround"

var _ReadPolicy_index = [...]uint8{0, 11, 29, 39}

func (i ReadPolicy) String() string {
	if i >= ReadPolicy(len(_ReadPolicy_index)-1) {
		return "ReadPolicy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReadPolicy_name[_ReadPolicy_index[i]:_ReadPolicy_index[i+1]]
}
