// Copyright 2021 The June Authors. All rights reserved.
// Use of this source code is governed by Apache License
// that can be found in the LICENSE file.

// Code generated by "stringer -type=WritePolicy"; DO NOT EDIT.

package storestacked

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WriteThrough-0]
	_ = x[WriteAround-1]
}

const _WritePolicy_name = "WriteThroughWriteAround"

var _WritePolicy_index = [...]uint8{0, 12, 23}

func (i WritePolicy) String() string {
	if i >= WritePolicy(len(_WritePolicy_index)-1) {
		return "WritePolicy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WritePolicy_name[_WritePolicy_index[i]:_WritePolicy_index[i+1]]
}
